package util;

import java.util.ArrayList;
import java.util.Arrays;

import lombok.Getter;

/**
 * Clase que contienen 
 * la segunda parte de los
 * instrumentos 
 * GARANTIAS
 * DERIVADOS
 * LINEAS NO COMPROMENTIDAS
 * OVERDRAFST
 * LEASING -REATING
 * LINEAS COMPROMETIDAS
 * 
 */
public class ConstanstUtils {

	/**
	 * Getter
	 * array que almacena instrumentos garantias
	 */
	@Getter
	private ArrayList<String> garantia = new ArrayList<>(Arrays.asList("GARANTIA ACCIONES COTIZADAS",
			"GARANTIA AVAL FINANCIERO - NO USAR (3Q 2016)", "GARANTIA DERECHOS DE COBRO",
			"GARANTIA PERSONAL MANCOMUNADA", "GARANTIA PERSONAL SOLIDARIA", "GARANTIA PERSONAL SOLIDARIA FINAN",
			"OTRAS GARANTIAS EN EFECTIVO", "OTRAS GARANTIAS REALES NO LIQUIDAS", "OTHER GUARANTY CASH"));
	/**
	 * Getter
	 * array que almacena instrumentos derivados
	 */
	@Getter
	private ArrayList<String> deriva = new ArrayList<>(Arrays.asList("ASSET SWAP", "CALL MONEY SWAP FLOATING FLOATING",
			"CALL MONEY SWAP FLOATING LONG", "CALL MONEY SWAP PAYER", "CALL MONEY SWAP RECEIVER",
			"CERTIFICATES OF DEPOSIT", "COLLAR KIKO", "COLLATERAL EQUITY", "COMMODITY FUTURES MMOO",
			"COMMODITY OPTIONS MMOO", "COMMODITY SWAP", "CREDIT DEFAULT SWAP - BOUGHT", "CREDIT DEFAULT SWAP - SOLD",
			"CREDIT DEFAULT SWAP UNDERLYING", "CURRENCY SWAPS", "DESCUBIERTOS CUENTAS VOSTRO", "EQUITY FORWARD",
			"EQUITY FUTURES MMOO", "EQUITY OPTION INDEX", "EQUITY OPTIONS", "EQUITY OPTIONS MMOO", "EQUITY SPOT",
			"EQUITY STOCK LENDING FOP", "EQUITY STOCK LENDING GBP", "EQUITY SWAPS", "FIXED INCOME LENDING UNDERLYING",
			"FIXED INFLATION SWAP PAYER", "FIXED INFLATION SWAP RECEIVER", "FLOATING RATE NOTES", "FORWARD ACOTADO",
			"FX - FORWARD", "FX - FORWARD AMERICANO", "FX  FUTURES MMOO", "FX - SPOT", "FX - SWAPS",
			"FX OPTIONS - MMOO", "FX OPTIONS - OTC", "FXTARKO", "GOVERNMENT SECURITIES", "INDEXED LINKED SWAP PAYER",
			"INDEXED LINKED SWAPRECEIVER", "INFLATION INTEREST RATE CAP", "INFLATION INTEREST RATE FLOOR",
			"INFLATION SWAP GENERIC DEALS", "INFLATION SWAP PAYER REVENUE", "INFLATION SWAP PAYER YEAR ON YEAR",
			"INFLATION SWAP PAYER ZERO COUPON", "INFLATION SWAP RECEIVER REVENUE",
			"INFLATION SWAP RECEIVER YEAR ON YEAR", "INFLATION SWAP RECEIVER ZERO COUPON", "INITIAL MARGIN CASH",
			"INITIAL MARGIN CASH 3TH PARTY", "INITIAL MARGIN EQUITY", "INTEREST RATE CAP", "INTEREST RATE FLOOR",
			"INTEREST RATE FORWARDS - FRA", "INTEREST RATE FUTURE - MMOO", "INTEREST RATE SWAP FLOATING FLOATING",
			"INTEREST RATE SWAP FLOATING LONG", "INTEREST RATE SWAP FLOATING SHORT", "INTEREST RATE SWAP PAYER",
			"INTEREST RATE SWAP RECEIVER", "INTEREST RATE SWAPS", "INTEREST RATE SWAPTIONS", "MONEY MARKET DEPOSITS",
			"MONEY MARKET PLACEMENTS", "MORTGAGE BACKED SECURITIES", "NON DELIVERABLE FORWARD", "OPTIONS RECEIVER",
			"OPTIONSPAYER", "SALDO EN CUENTAS NOSTRO", "SECURED FIXED INCOME LENDING",
			"SECURED FIXED INCOME LENDING FOP", "SECURED STOCK LENDING FOP", "SERIAL ZERO COUPON PAYER",
			"SERIAL ZERO COUPON RECEIVER", "SWAP BONIFICADO SAME FREQ", "SWAP FORWARD INFLACION",
			"TITULIZACION DE HIPOTECAS", "UNSECURED FIXED INCOME LENDING", "UNSECURED STOCK LENDING",
			"VARIATION MARGIN CASH", "VARIATION MARGIN CASH 3TH PARTY", "ZERO COUPON SWAP PAYER",
			"ZERO COUPON SWAPRECEIVER", "CURRENCY SWAP"

	));

	/**
	 * Getter
	 * array que almacena instrumentos 
	 * creditos no comprometidos
	 */
	@Getter
	private ArrayList<String> nocomprome = new ArrayList<>(Arrays.asList("CREDITOS - NO COMPROMETIDO"));
	/**
	 * Getter
	 * array que almacena instrumentos 
	 * overdrafts
	 */
	@Getter
	private ArrayList<String> overdraf = new ArrayList<>(Arrays.asList("OVERDRAFTS"));
	/**
	 * Getter
	 * array que almacena instrumentos 
	 * leasing renting
	 */
	@Getter
	private ArrayList<String> learent = new ArrayList<>(Arrays.asList("LEASING", "RENTING"));
	
	/**
	 * Getter
	 * array que almacena instrumentos lineas compormetidas
	 */
	@Getter
	private ArrayList<String> comprome = new ArrayList<>(Arrays.asList("LINEA MULTIDEAL RESTO - COMPROMETIDO",
			"CREDITOS - COMPROMETIDO", "CREDITO BACKUP - COMPROMETIDO - NO USAR (3Q 2016)",
			"CREDITO OTROS - COMPROMETIDO - NO USAR (3Q 2016)"));
	
	
	
}
